*** Settings ***
Documentation    Aqui está contida todas as variáveis que fazem parte da funcionalidade de cadastro
Library    SeleniumLibrary

*** Variables ***
#ELEMENTOS
${bt_adicionar}    id:add-to-cart-button
${bt_comprar_agora}    id:buy-now-button
${contador_carrinho}    id:nav-cart-count
${acessar_carrinho}    id:nav-cart-count-container
${bt_fechar_pedido}    id:sc-buy-box-ptc-button-announce
${campo_qtd_produto}    id:quantity


